name: CI

on:
  push:
    branches:
      - ns_impl
  pull_request:
    branches:
      - ns_impl

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ns_impl  # Explicitly checking out the 'ns_impl' branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
          pip install gymnasium[atari, accept-rom-license]

      - name: Run tests
        run: pytest tests/*
